export const gameData=[
    {
        name:"lion",
        src:'./lion.jpg',
        id:0,
        shown:false
    },
    {
        name:"cat",
        src:'./cat.png',
        id:1,
        shown:false
    },
    {
        name:"dear",
        src:'./dear.jpg',
        id:2,
        shown:false
    },
    {
        name:"fox",
        src:'./fox.png',
        id:3,
        shown:false
    },
    {
        name:"girl",
        src:'./girl.png',
        id:4,
        shown:false
    },
    {
        name:"panda",
        src:'./panda.jpg',
        id:5,
        shown:false
    },
    {
        name:"lion",
        src:'./lion.jpg',
        id:6,
        shown:false
    },
    {
        name:"cat",
        src:'./cat.png',
        id:7,
        shown:false
    },
    {
        name:"dear",
        src:'./dear.jpg',
        id:8,
        shown:false
    },
    {
        name:"fox",
        src:'./fox.png',
        id:9,
        shown:false
    },
    {
        name:"girl",
        src:'./girl.png',
        id:10,
        shown:false
    },
    {
        name:"panda",
        src:'./panda.jpg',
        id:11,
        shown:false
    },
]